steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/quevino-knowledge-stores', '-f', 'apis/knowledge_stores/deploy/Dockerfile', 'apis/knowledge_stores/']
  
  # Push the image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/quevino-knowledge-stores']
  
  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'quevino-knowledge-stores'
      - '--image'
      - 'gcr.io/$PROJECT_ID/quevino-knowledge-stores'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--service-account'
      - 'cloud-run-apis@que-vino-23032025.iam.gserviceaccount.com'
      - '--max-instances'
      - '1'

images:
  - 'gcr.io/$PROJECT_ID/quevino-knowledge-stores'
